blog/ViewModels/EditPostViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace blog.ViewModels
{
    public class EditPostViewModel
    {
        [MaxLength(30)]
        [Required]
        public string Title { get; set; }

        [MaxLength(1000)]
        [Required]
        public string Content { get; set; }

        public int Id { get; set; }
    }
}

blog/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace blog.ViewModels
{
    public class LoginViewModel
    {
        [MaxLength(30, ErrorMessage = "Max 30 tecken")]
        [MinLength(4, ErrorMessage = "Minst 4 tecken")]
        [Required]
        public string Login { get; set; }

        [MinLength(4, ErrorMessage = "Minst 4 tecken")]
        [DataType(DataType.Password)]
        [Required]
        public string Password { get; set; }
    }
}

blog/ViewModels/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace blog.ViewModels
{
    public class RegisterViewModel
    {
        [MaxLength(30, ErrorMessage = "Max 30 tecken")]
        [MinLength(4, ErrorMessage = "Minst 4 tecken")]
        [Required]
        public string Login { get; set; }

        [MinLength(4, ErrorMessage = "Minst 4 tecken")]
        [DataType(DataType.Password)]
        [Required]
        public string Password { get; set; }

        [MinLength(4, ErrorMessage = "Minst 4 tecken")]
        [DataType(DataType.Password)]
        [Required]
        [Compare(nameof(Password),ErrorMessage = "Lösenorden matchar inte")]
        public string ConfirmPassword { get; set; }
    }
}

blog/ViewModels/SavePostViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace blog.ViewModels
{
    public class SavePostViewModel
    {
        [MaxLength(30)]
        [Required]
        public string Title { get; set; }

        [MaxLength(1000)]
        [Required]
        public string Content { get; set; }

    }
}

blog/Controllers/BlogPostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Data.Context;
using Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using blog.ViewModels;

namespace blog.Controllers
{
    [Authorize]
    public class BlogPostController : Controller
    {
        private readonly IBlogContext _blogContext;

        public BlogPostController(IBlogContext blogContext)
        {
            _blogContext = blogContext;
        }

        [AllowAnonymous]
        public IActionResult Delete(int id)
        {
            var post = _blogContext.Posts.Find(id);
            _blogContext.Posts.Remove(post);
            _blogContext.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult NewPost()
        {
            return View("NewPost");
        }

        [HttpPost]
        public IActionResult NewPost(SavePostViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var user = _blogContext.Users.FirstOrDefault(uss => uss.Name == User.Identity.Name);
                if (user != null)
                {
                    var post = new Post() { Title = viewModel.Title, Text = viewModel.Content, UserId = user.UserId };
                    _blogContext.Posts.Add(post);
                    _blogContext.SaveChanges();
                }
                else
                {
                    ModelState.AddModelError("", "Fuck!");
                    return View(viewModel);
                }
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var post = _blogContext.Posts.Find(id);
            var viewModel = new EditPostViewModel(){Content = post.Text, Title = post.Title, Id = post.Id};

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(EditPostViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var post = _blogContext.Posts.Find(viewModel.Id);
                post.Title = viewModel.Title;
                post.Text = viewModel.Content;
                _blogContext.Posts.Update(post);
                _blogContext.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(viewModel);
        }
    }
}

blog/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using blog.ViewModels;
using Data.Context;
using Domain.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace blog.Controllers
{
    public class HomeController : Controller
    {

        private readonly IBlogContext _blogContext;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public HomeController(IBlogContext blogContext, UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _blogContext = blogContext;
            _userManager = userManager;
            _signInManager = signInManager;
        }



        [HttpGet]
        public IActionResult Index()
        {
            var posts = _blogContext.Posts.ToList();
            return View(posts);
        }

        [HttpGet]
        public IActionResult Login()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var signIn = await _signInManager.PasswordSignInAsync(viewModel.Login, viewModel.Password, false, false);
                if (signIn.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", "Användaren existerar inte");
                }
            }
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel viewModel)
        {
            if (ModelState.IsValid)
            {

                IdentityResult identityResult;
                var user = new User()
                { Name = viewModel.Login, UserName = viewModel.Login };
                try
                {
                    identityResult = await _userManager.CreateAsync(user, viewModel.Password);
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Fuck!");
                    return View(viewModel);
                }

                if (identityResult.Succeeded)
                {
                    await _signInManager.SignInAsync(user, false);
                    return RedirectToAction(nameof(Index));
                }

                foreach (var identityResultError in identityResult.Errors)
                {
                    ModelState.AddModelError("", identityResultError.Description);
                }
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

blog/ViewComponents/NavBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace blog.ViewComponents
{
    public class NavBarViewComponent : ViewComponent
    {

        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

blog/Views/BlogPost/Edit.cshtml
@model EditPostViewModel

@{
    ViewBag.Title = "Redigera blogginlägg";
}

<!DOCTYPE html>

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-10">
                <br />
                <br />
                <form method="post">
                    <input asp-for="Title" type="text" class="input-lg" placeholder="Bloggtitel" value="@Model.Title" />
                    <input type="hidden" asp-for="Id"/>
                    <br />
                    <br />
                    <textarea asp-for="Content" class="form-control" rows="10" placeholder="Bloggtext">@Model.Content</textarea>
                    <br />
                    <input value="Spara" class="btn btn-success" type="submit" />
                </form>
            </div>
            <div class="col-sm-1"></div>
        </div>
    </div>
    <hr />
</section>

blog/Views/BlogPost/NewPost.cshtml
@model SavePostViewModel

@{
    ViewBag.Title = "Nytt blogginlägg";
}

<!DOCTYPE html>

<section>
        <div class="container">
            <div class="row">
                <div class="col-sm-1"></div>
                <div class="col-sm-10">
                    <br />
                    <br />
                    <form method="post">
                        <input asp-for="Title" type="text" class="input-lg" placeholder="Bloggtitel"/>
                        <br/>
                        <br/>
                        <textarea asp-for="Content" class="form-control" rows="10" placeholder="Bloggtext"></textarea>
                        <br/>
                       <input value="Publicera" class="btn btn-success" type="submit" />
                    </form>
                </div>
                <div class="col-sm-1"></div>
            </div>
        </div>
    <hr />
</section>

blog/Views/Home/Index.cshtml
@model IEnumerable<Domain.Entities.Post>

<div>
    
    @foreach (var post in Model)
    {
        @Html.Partial("_blogPostSummary", post)
    }
</div>

blog/Views/Home/Login.cshtml
@model LoginViewModel
@{
    ViewBag.Title = "Logga in";
}

<div class="container container-fluid">
    <section class="panel panel-default">
        

        <div asp-validation-summary="All"></div>
        <form asp-antiforgery="true" method="post">
            <h2>Logga in</h2>
            <div class="panel-body">
                <input asp-for="Login" class="input-lg" placeholder="Användarnamn"/>
                <input asp-for="Password" class="input-lg" placeholder="Lösenord"/>
            </div>
            <div class="panel-footer">
                <input asp-action="Login" asp-controller="Home"class="btn btn-primary" value="Logga in" type="submit"/>
                <a asp-action="Register" asp-controller="Home">Registrera</a>
            </div>
        </form>
    </section>
</div>

blog/Views/Home/Register.cshtml
@model RegisterViewModel
@{
    ViewBag.Title = "Registrera";
}
<div class="container container-fluid">
    <section class="panel panel-default">


        <div asp-validation-summary="All"></div>
        <form asp-antiforgery="true" method="post">
            <h2>Registrera ny användare</h2>
            <div class="panel-body">
                <div class="input-group">
                    <input asp-for="Login" class="input-lg inputMargin" placeholder="Användarnamn" /><br/>
                    <input asp-for="Password" class="input-lg inputMargin" placeholder="Lösenord" /><br/>
                    <input asp-for="ConfirmPassword" class="input-lg inputMargin" placeholder="Upprepa lösenord" /><br/>
                </div>
            </div>
            <div class="panel-footer">
                <input asp-action="Register" asp-controller="Home" class="btn btn-primary" value="Registrera" type="submit" />
            </div>
        </form>
    </section>
</div>

blog/Views/Home/_blogPostSummary.cshtml
@model Domain.Entities.Post

<section>
    <article>
        
        <div class="container">
            <div class="row">
                <div class="col-sm-1"></div>
                <div class="col-sm-10">
                    <br/>
                    <br/>
                    <h1><b>@Model.Title</b>
                    </h1>
                    <h4>@Model.DateCreated.Date.ToString("D")</h4>
                    <br/>
                    <p>@Model.Text</p>
                </div>
                <div class="col-sm-1"></div>
            </div>

        </div>
    </article>
    <a asp-route-id="@Model.Id" asp-action="Delete" asp-controller="BlogPost"class="btn btn-danger">Ta bort</a>
    <a asp-route-id="@Model.Id" asp-action="Edit" asp-controller="BlogPost" class="btn btn-danger">Redigera</a>

    <hr/>

</section>

blog/Views/Shared/Components/NavBar/Default.cshtml
<nav class="navbar navbar-inverse navbar-fixed-top" style="height: 50px">
    <div class="container-fluid">
        <a class="navbar-brand">Mattias blogg</a>

        @if (User.Identity.IsAuthenticated)
        {
            <a asp-action="Logout" asp-controller="Home" class="navbar-brand glyphicon-bitcoin pull-right">Log out</a>
            <a asp-action="NewPost" asp-controller="BlogPost" class="navbar-brand glyphicon-btc pull-right">New Post</a>
        }
        else
        {
            <a asp-controller="Home" asp-action="Login" class="navbar-brand glyphicon-bitcoin pull-right">Log in</a>
        }


    </div>
</nav>

blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <link href="~/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/Style.css" rel="stylesheet" />
</head>
<body>
@await Component.InvokeAsync("NavBar")
    <div class="contentSpacingTop"></div>
<div id="main-content">
    @RenderBody()
</div>
</body>

</html>